export const trainData = [
  {
    train_number: "12465",
    train_name: "Ranthambhore SF Express",
    run_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    train_src: "INDB",
    train_dstn: "JU",
    from_std: "12:35",
    from_sta: "12:25",
    local_train_from_sta: 745,
    to_sta: "16:35",
    to_std: "16:50",
    from_day: 0,
    to_day: 0,
    d_day: 0,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 8,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "4:00",
    special_train: false,
    train_type: "SUF",
    score: 23,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 1,
    score_duration: 8,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A"],
  },
  {
    train_number: "12955",
    train_name: "Mumbai Central - Jaipur SF Express",
    run_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    train_src: "MMCT",
    train_dstn: "JP",
    from_std: "07:55",
    from_sta: "07:45",
    local_train_from_sta: 1905,
    to_sta: "12:00",
    to_std: "12:00",
    from_day: 1,
    to_day: 1,
    d_day: 1,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 2,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "4:05",
    special_train: false,
    train_type: "SUF",
    score: 23,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 1,
    score_duration: 8,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["2S", "SL", "3A", "2A", "1A"],
  },
  {
    train_number: "07123",
    train_name: "Secunderabad - Udaipur City",
    run_days: ["Thu"],
    train_src: "SC",
    train_dstn: "UDZ",
    from_std: "05:05",
    from_sta: "04:55",
    local_train_from_sta: 3175,
    to_sta: "09:15",
    to_std: "09:25",
    from_day: 2,
    to_day: 2,
    d_day: 2,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 1,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "4:10",
    special_valid_to: "2024-06-27",
    special_train: true,
    train_type: "MEX",
    score: 23,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 1,
    score_duration: 8,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A", "2A", "1A"],
  },
  {
    train_number: "22997",
    train_name: "Jhalawar City - Shri Ganganagar SF Express",
    run_days: ["Wed", "Thu", "Sun"],
    train_src: "JLWC",
    train_dstn: "SGNR",
    from_std: "17:20",
    from_sta: "17:10",
    local_train_from_sta: 1030,
    to_sta: "21:30",
    to_std: "21:40",
    from_day: 0,
    to_day: 0,
    d_day: 0,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 8,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "4:10",
    special_train: false,
    train_type: "SUF",
    score: 21,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 1,
    score_duration: 6,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A", "2A", "1A", "3E"],
  },
  {
    train_number: "12967",
    train_name: "MGR Chennai Central - Jaipur SF Express",
    run_days: ["Thu", "Tue"],
    train_src: "MAS",
    train_dstn: "JP",
    from_std: "02:30",
    from_sta: "02:20",
    local_train_from_sta: 3020,
    to_sta: "06:45",
    to_std: "06:45",
    from_day: 2,
    to_day: 2,
    d_day: 2,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 2,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "4:15",
    special_train: false,
    train_type: "SUF",
    score: 21,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 1,
    score_duration: 6,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A", "2A", "1A", "3E"],
  },
  {
    train_number: "12939",
    train_name: "PUNE - JAIPUR SF Express",
    run_days: ["Thu", "Mon"],
    train_src: "PUNE",
    train_dstn: "JP",
    from_std: "10:25",
    from_sta: "10:15",
    local_train_from_sta: 2055,
    to_sta: "14:40",
    to_std: "14:40",
    from_day: 1,
    to_day: 1,
    d_day: 1,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 3,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "4:15",
    special_train: false,
    train_type: "MAIL EXPRESS",
    score: 21,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 1,
    score_duration: 6,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["2S", "SL", "3A", "2A", "1A", "3E"],
  },
  {
    train_number: "12181",
    train_name: "Dayodaya SF Express",
    run_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    train_src: "JBP",
    train_dstn: "AII",
    from_std: "07:10",
    from_sta: "06:50",
    local_train_from_sta: 1850,
    to_sta: "11:30",
    to_std: "11:40",
    from_day: 1,
    to_day: 1,
    d_day: 1,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 6,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "4:20",
    special_train: false,
    train_type: "SUF",
    score: 21,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 1,
    score_duration: 6,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A", "2A", "1A", "3E"],
  },
  {
    train_number: "19813",
    train_name: "Kota - Sirsa Express",
    run_days: ["Mon", "Thu", "Sat"],
    train_src: "KOTA",
    train_dstn: "SSA",
    from_std: "23:45",
    from_sta: "23:45",
    local_train_from_sta: 1425,
    to_sta: "04:50",
    to_std: "05:00",
    from_day: 0,
    to_day: 1,
    d_day: 0,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 9,
    distance: 240,
    to_station_name: "JAIPUR",
    duration: "5:05",
    special_train: false,
    train_type: "MEX",
    score: 19,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 2,
    score_duration: 4,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A", "2A", "3E"],
  },
  {
    train_number: "01433",
    train_name: "PUNE DKBJ SPL",
    run_days: ["Thu"],
    train_src: "PUNE",
    train_dstn: "DKBJ",
    from_std: "01:35",
    from_sta: "01:30",
    local_train_from_sta: 1530,
    to_sta: "07:10",
    to_std: "07:20",
    from_day: 1,
    to_day: 1,
    d_day: 1,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 2,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "5:35",
    special_valid_to: "2099-12-28",
    special_train: true,
    train_type: "MAIL EXPRESS",
    score: 19,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 2,
    score_duration: 4,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A", "2A", "1A"],
  },
  {
    train_number: "14814",
    train_name: "Bhopal - Jodhpur Express",
    run_days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    train_src: "BPL",
    train_dstn: "JU",
    from_std: "02:45",
    from_sta: "02:20",
    local_train_from_sta: 1580,
    to_sta: "10:45",
    to_std: "10:55",
    from_day: 1,
    to_day: 1,
    d_day: 1,
    from: "KOTA",
    to: "JP",
    from_station_name: "KOTA JN",
    halt_stn: 18,
    distance: 239,
    to_station_name: "JAIPUR",
    duration: "8:0",
    special_train: false,
    train_type: "MEX",
    score: 19,
    score_train_type: 5,
    score_booking_requency: 0,
    frequency_perc: 0,
    from_distance_text: "",
    to_distance_text: "",
    duration_rating: 4,
    score_duration: 4,
    score_std: 10,
    score_user_preferred: 0,
    train_date: "13-06-2024",
    class_type: ["SL", "3A"],
  },
];

export const dummyStations = [
  {
    name: "KASIM KOTA HALT",
    eng_name: "KASIM KOTA HALT",
    code: "KCH",
    state_name: "ANDHRA PRADESH",
  },
  {
    name: "KOTA C CABIN",
    eng_name: "KOTA C CABIN",
    code: "KCCN",
    state_name: "Rajasthan",
  },
  {
    name: "KOTA CITY",
    eng_name: "KOTA CITY",
    code: "KTCY",
    state_name: "",
  },
  {
    name: "KOTA JN",
    eng_name: "KOTA JN",
    code: "KOTA",
    state_name: "RAJASTHAN",
  },
  {
    name: "KOTA JN SOUTH C",
    eng_name: "KOTA JN SOUTH C",
    code: "KTSC",
    state_name: "RAJASTHAN",
  },
  {
    name: "KOTA WORKSHOP",
    eng_name: "KOTA WORKSHOP",
    code: "KTTW",
    state_name: "Rajasthan",
  },
  {
    name: "KOTA YARD",
    eng_name: "KOTA YARD",
    code: "KTTY",
    state_name: "RAJASTHAN",
  },
  {
    name: "KOTABOMMALI",
    eng_name: "KOTABOMMALI",
    code: "KBM",
    state_name: "ANDHRA PRADESH",
  },
  {
    name: "KOTAKADRA",
    eng_name: "KOTAKADRA",
    code: "KTKA",
    state_name: "TELANGANA",
  },
  {
    name: "KOTALA",
    eng_name: "KOTALA",
    code: "KEN",
    state_name: "ANDHRA PRADESH",
  },
  {
    name: "KOTALPUKUR",
    eng_name: "KOTALPUKUR",
    code: "KLP",
    state_name: "JHARKHAND",
  },
  {
    name: "KOTANA",
    eng_name: "KOTANA",
    code: "KTOA",
    state_name: "RAJASTHAN",
  },
  {
    name: "KOTAPAR ROAD",
    eng_name: "KOTAPAR ROAD",
    code: "KPRR",
    state_name: "ODISHA",
  },
  {
    name: "KOTARLIA",
    eng_name: "KOTARLIA",
    code: "KRL",
    state_name: "CHHATISGARH",
  },
  {
    name: "GANDHINAGAR JAIPUR",
    eng_name: "GANDHINAGAR JAIPUR",
    code: "GADJ",
    state_name: "RAJASTHAN",
  },
  {
    name: "GARH JAIPUR",
    eng_name: "GARH JAIPUR",
    code: "GUG",
    state_name: "WEST BENGAL",
  },
  {
    name: "JAIPUR",
    eng_name: "JAIPUR",
    code: "JP",
    state_name: "RAJASTHAN",
  },
  {
    name: "JAIPUR JN MG",
    eng_name: "JAIPUR JN MG",
    code: "JPF",
    state_name: "RAJASTHAN",
  },
];

export const seats3A = [
  {
    ticket_fare: 555,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 555,
    date: "13-6-2024",
    current_status: "AVAILABLE-0160",
  },
  {
    ticket_fare: 555,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 555,
    date: "14-6-2024",
    current_status: "AVAILABLE-0163",
  },
  {
    ticket_fare: 555,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 555,
    date: "15-6-2024",
    current_status: "AVAILABLE-0136",
  },
  {
    ticket_fare: 555,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 555,
    date: "16-6-2024",
    current_status: "AVAILABLE-0141",
  },
  {
    ticket_fare: 555,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 555,
    date: "17-6-2024",
    current_status: "AVAILABLE-0155",
  },
  {
    ticket_fare: 555,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 555,
    date: "18-6-2024",
    current_status: "AVAILABLE-0163",
  },
];

export const seatsSL = [
  {
    ticket_fare: 210,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 210,
    date: "13-6-2024",
    current_status: "AVAILABLE-0054",
  },
  {
    ticket_fare: 210,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 210,
    date: "14-6-2024",
    current_status: "AVAILABLE-0052",
  },
  {
    ticket_fare: 210,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 210,
    date: "15-6-2024",
    current_status: "AVAILABLE-0029",
  },
  {
    ticket_fare: 210,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 210,
    date: "16-6-2024",
    current_status: "AVAILABLE-0052",
  },
  {
    ticket_fare: 210,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 210,
    date: "17-6-2024",
    current_status: "AVAILABLE-0041",
  },
  {
    ticket_fare: 210,
    catering_charge: 0,
    alt_cnf_seat: false,
    total_fare: 210,
    date: "18-6-2024",
    current_status: "AVAILABLE-0051",
  },
];

export const coachData = [
  {
    name: "AC First Class",
    nameWithCode: "AC First Class (1A)",
    code: "1A",
  },
  {
    name: "AC 2 Tier",
    nameWithCode: "AC 2 Tier (2A)",
    code: "2A",
  },
  {
    name: "AC 3 Tier",
    nameWithCode: "AC 3 Tier (3A)",
    code: "3A",
  },
  {
    name: "AC 3 Economy",
    nameWithCode: "AC 3 Economy (3E)",
    code: "3E",
  },
  {
    name: "Sleeper",
    nameWithCode: "Sleeper (SL)",
    code: "SL",
  },
  {
    name: "Second Sitting",
    nameWithCode: "Second Sitting (2S)",
    code: "2S",
  },
];
